export const CURRENT_POSISTION_CHANGED = "CURRENT_POSISTION_CHANGED";
export type CURRENT_POSISTION_CHANGED = typeof CURRENT_POSISTION_CHANGED;

export const LOAD_MARKERS = "LOAD_MARKERS";
export type LOAD_MARKERS = typeof LOAD_MARKERS;

export const MARKERS_REQUESTED = "MARKERS_REQUESTED";
export type MARKERS_REQUESTED = typeof MARKERS_REQUESTED;

export const MARKERS_LOADED = "MARKERS_LOADED";
export type MARKERS_LOADED = typeof MARKERS_LOADED;

export const CENTER_CHANGED = "CENTER_CHANGED";
export type CENTER_CHANGED = typeof CENTER_CHANGED;

export const FILTER_CHANGED = "FILTER_CHANGED";
export type FILTER_CHANGED = typeof FILTER_CHANGED;