export const CURRENT_POSISTION_CHANGED = "CURRENT_POSISTION_CHANGED";
export const LOAD_MARKERS = "LOAD_MARKERS";
export const MARKERS_REQUESTED = "MARKERS_REQUESTED";
export const MARKERS_LOADED = "MARKERS_LOADED";
export const CENTER_CHANGED = "CENTER_CHANGED";
export const FILTER_CHANGED = "FILTER_CHANGED";